### ISSUE TITLE
请求支持最新版6.3.13_r4488992

### ISSUE THREAD

**Issue by 424778940z** [Chion82/WeChatMomentExport#1]
GooglePlay更新了微信版本号变为6.3.13_r4488992,跟前一个版本应该没有什么区别吧,...
求更新,现在按了可以开始抓取但实际上并没有生成文件...

**Comment by Chion82** [comment]
最近会更新，还请稍等。如果版本不对的话点开始抓取是没有用的

**Comment by Chion82** [comment]
@424778940z 已更新
