### ISSUE TITLE
Some questions abaout export results

### ISSUE THREAD

**Issue by wangyj1** [Chion82/WeChatMomentExport#2]
有几个问题：

1.打开朋友圈，并不能导出微信朋友圈的信息。进入某个朋友的朋友圈，只能导出五六条数据，然后就没有数据了。但app中显示抓取了一百多条。不知是程序的bug,还是设置的问题。Android 4.2.2  微信6.3.13.49  微信朋友圈导出工具 2.1beta
2. 能否为ios开发cydia插件。不知微信朋友圈的数据结构在ios和Android是否相同。

**Comment by Chion82** [comment]
app界面显示的抓取数量是实时从导出的文件中读到的，理论上不存在导出文件的条目数与界面显示不相符的情况。注意，在点击开始抓取后，原导出文件会被清空。可能是你再次点击开始抓取后，在xposed模块还没有抓到数据时，界面中显示的100多条是上次抓取的结果(这时原导出文件还没被覆盖)，而当再次进入微信，抓到数据时，之前的100多条会被覆盖，可能此时只有5条记录被抓到。所以每次抓取应该在点击停止抓取后尽快拷贝导出的文件避免结果被覆盖。因为是实验性的项目，在用户体验上可能较差，望理解
另外目前还没有ios的开发计划
