### ISSUE TITLE
Hook onto wechat refresh and auto-load?

### ISSUE THREAD

**Issue by thisiscam** [Chion82/WeChatMomentExport#3]
Hi @Chion82,

This project is great! However, just as a suggestions, I would like to see the functionality of something like one-click export of, say, some user provided number of moments. I'm not sure if it will be easy, but from description of Xposed, this seems doable. 

This will be very appreciated since I was thinking of doing some mining on my moments :)

Thanks and Best

**Comment by Chion82** [comment]
Sure it is plausible. I am working on another repository `WeChatMomentStat-Android` which gets moments from WeChat SQLite cache with just an one-click. However getting cache parsers from WeChat dex-classes or hooking parser methods is a little bit difficult and it will take some time to finish.

**Comment by thisiscam** [comment]
Ok Thanks

Hope your work will be out soon!
